name: build
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@master
        with:
          args: "package -o /tmp/vscode-R.vsix"
      - uses: actions/upload-artifact@v1
        with:
          name: vsix
          path: /tmp/vscode-R.vsix
