name: main
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@master
        with:
          args: "package -o vscode-R.vsix"
      - uses: actions/upload-artifact@v1
        with:
          name: vsix
          path: vscode-R.vsix
  tslint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "src/*.ts"
  lintr:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install apt-get dependencies
        run: |
          apt-get update
          apt-get install git ssh curl bzip2 libffi6 libffi-dev -y
      - name: Install lintr
        run: |
          Rscript -e "install.packages('lintr', repos = 'https://cloud.r-project.org')"
        shell: bash
      - name: Running lintr
        run: |
          Rscript -e "lintr::lint_dir('./R')"
        shell: bash
